                                                 GROUP 3
                                    NAGAWA ESTHER.REG NO:2023/DCSE/0049/SS
                                    NANSALIRE ANITAH.REG NO:2023/DCSE/0079/SS
                                    AKAPO REGINAH EBAJU. REG NO:2023/DCSE/006/SS
                                    AMUTUHAIRE FAITH AHABWE. REG NO:2023/DCSE/0011/SS
                                    LWAMULUNGI SHEILAH. REG NO:2023/DCSE/0037/SS
                                    NAMUDDU MARIAM. REG NO:2023/DCSE/00105/SS

# 1) LINEAR ALGEBRA

What is linear algebra in simple words?
Linear algebra is the study of linear combinations. It is the study of vector spaces, lines and planes, and some mappings that are required to perform the linear transformations. It includes vectors, matrices and linear functions. It is the study of linear sets of equations and its transformation properties.

In [49]:

#Solving linear equations (Ab=c)
import numpy as np


In [50]:
# Define matrix A and vector c
A = np.array([[2, 1], [5, 3]])
c = np.array([1, 2])

# Solve for x
b= np.linalg.solve(A, c)

print("Solution b:")
print(b)

Solution b:
[ 1. -1.]


# 2) VECTORS,COMBINING AND SCALING

# VECTORS

In [ ]:

A vector is an object that has both magnitude and direction but not position e.g) (a,-b)=a+b

Combining is the number of ways that a certain number of objects can be taken from a lager number of objects;if the order does not matter.

Scaling is a procedure through which we draw an object that is proportional to actual size of the object.


In [2]:
# VECTORS
import numpy as np

In [5]:
# Define two vectors
vectora=np.array([6,7,8])
vectorb=np.array([9,2,3])

#Vector addition
result_add=vectora + vectorb
print("vector addition:" ,result_add)

vector addition: [15  9 11]


In [6]:
# vector subtraction
result_sub=vectora -vectorb
print("vector subtraction:",result_sub)

vector subtraction: [-3  5  5]


# COMBINING

In [ ]:
# Combining a vector
combined_vector=np.concatenate(vectora,vectorb)
print("combined_vector")

In [11]:
# stack vectors horizontally
stacked_vector=np.hstack((vectora,vectorb))
print("stacked vector (horizontal):",stacked_vector)

stacked vector (horizontal): [6 7 8 9 2 3]


In [10]:
# stack vectors vertically
stacked_vector=np.vstack((vectora,vectorb))
print("stacked vector(horizontal):",stacked_vector)

stacked vector(horizontal): [[6 7 8]
 [9 2 3]]


# SCALING

In [9]:
# Scaling a vector
scaling_factor=4
scaled_vector=vectora*vectorb
print("scaled vector:",scaled_vector)

scaled vector: [54 14 24]


# 3) TRANSFORMING VECTORS AND MATRICES

To transform a vector, we need to multiply the transformation matrix with that vector. This would result in a transformed vector, where the length or direction of the vector may be changed.

In [4]:
import numpy as np

# Define a 2D vector
vector = np.array([6,7])

# Translation by (dx, dy)
dx, dy = 3,4
translation_matrix = np.array([[3, 0, dx],
                               [0, 3, dy]])

# Apply translation
translated_vector = np.dot(translation_matrix, np.append(vector, 3))[:4]

print("Original Vector:", vector)
print("Translated Vector:", translated_vector)

Original Vector: [6 7]
Translated Vector: [27 33]


In [5]:
import numpy as np
import math

# Define a 2D vector
vector = np.array([7,8])

# Rotation angle in radians
theta = math.pi / 4  # 45 degrees

# Rotation matrix
rotation_matrix = np.array([[math.cos(theta), -math.sin(theta)],
                             [math.sin(theta), math.cos(theta)]])

# Apply rotation
rotated_vector = np.dot(rotation_matrix, vector)

print("Original Vector:", vector)
print("Rotated Vector:", rotated_vector)

Original Vector: [7 8]
Rotated Vector: [-0.70710678 10.60660172]


In [6]:
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[4, 0],
                   [0, 6]])

# Scaling factors
sx, sy = 1.5, 0.5

# Scaling matrix
scaling_matrix = np.array([[sx, 0],
                            [0, sy]])

# Apply scaling
scaled_matrix = np.dot(scaling_matrix, matrix)

print("Original Matrix:\n", matrix)
print("Scaled Matrix:\n", scaled_matrix)

Original Matrix:
 [[4 0]
 [0 6]]
Scaled Matrix:
 [[6. 0.]
 [0. 3.]]


In [10]:
import numpy as np

# Define matrices
matrix_A = np.array([[7, 8],
                     [9, 6]])

matrix_B = np.array([[5, 4],
                     [2, 0]])

# Matrix multiplication
result_matrix = np.dot(matrix_A, matrix_B)

print("Matrix A:\n", matrix_A)
print("Matrix B:\n", matrix_B)
print("Result Matrix:\n", result_matrix)

Matrix A:
 [[7 8]
 [9 6]]
Matrix B:
 [[5 4]
 [2 0]]
Result Matrix:
 [[51 28]
 [57 36]]


# 4) SYSTEM OF LINEAR EQUATIONS AND INVERSE MATRICES

 Solving linear equations using inverse matrices

Write the system as a matrix equation: [coefficient matrix] [variables] = [constants].
Find the inverse of the coefficient matrix.
Multiply both sides by the inverse. It cancels with the coefficient matrix.
The result is [variables] = [inverse][constants]. Solving a system of linear equations using the inverse of a matrix requires the definition of two new matrices: 
X is the matrix representing the variables of the system, and B is the matrix representing the constants. Using matrix multiplication, we may define a system of equations with the same number of equations as variables as AX=B
To solve a system of linear equations using an inverse matrix, let A be the coefficient matrix, let X be the variable matrix, and let B be the constant matrix. Thus, we want to solve a system AX=B.
EXAMPLES
Example 1: In this example, we will create a 3 by 3 NumPy array matrix and then convert it into an inverse matrix using the np.linalg.inv() function.

In [3]:
# Import required package
import numpy as np
 
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


Example 2, Create a 4 by 4 NumPy array matrix and then convert it using np.linalg.inv() function into an inverse Matrix in Python.

In [ ]:
# Import required package
import numpy as np
 
# Taking a 4 * 4 matrix
A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])
 
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


# 5) DOT PRODUCTS

THE DOT PRODUCT
      Dot Product refers to the mathematical operation that takes two equal-length sequences of numbers (usually vectors) and returns a single number.

Its a fundamental operation in linear algebra and has operations in various fields such as engeneering and computer science as well.

#Exaple
    Given two vectors;
A = [a,b,c]
B = [1,2,3]
 the dot product A.B is calculated as follows;

 A.B = [a.1,b.2,c.3] in a mathematical notation.

      In a Numpy library,the operation is fundamental in vector and matrix operations and plays a cruicial role in various mathematical and computational operations. 

 
       

In [ ]:
import numpy as np

In [ ]:
vector_A = (1,2,3)

In [ ]:
vector_B = (4,5,6)

In [ ]:
vector_A = np.array([1,2,3])

In [ ]:
vector_B = np.array([4,5,6])

In [ ]:
np.dot(vector_A,vector_B)

32

# 6) MATRIX DECOMPOSITION

Matrix decomposition refers to the transformation of a given matrix into a given canonical form. [1],
when the given matrix is transformed to a right-hand-side product of canonical matrices the process of
producing this decomposition is also called “matrix factorization”. Matrix decomposition is a fundamental theme in linear algebra and applied statistics which has both scientific and engineering significance.
The purposes of matrix decomposition typically involve two aspects: computational convenience and analytic simplicity. In the real world, it is not feasible for most of the matrix computations to be calculated
in an optimal explicit way, such as matrix inversion, matrix determinant, solving linear system and least
square fitting, thus to convert a difficult matrix computation problem into several easier tasks such as
solving triangular or diagonal system will greatly facilitate the calculations. Data matrices representing
some numerical observations such as proximity matrix or correlation matrix are often huge and hard to
analyze, therefore to decompose the data matrices into some lower-order or lower-rank canonical forms
will reveal the inherent characteristic and structure of the matrices and help to interpret their meaning readily.
                            TYPES OF MATRIX DECOMPOSITION
                         1 LU DECOMPOSITION
                         2 QR DECOMPOSITION 
                         3 SINGULAR VALUE DECOMPOSTION
                         4 EINGVALUE DECOMPOSITION


# LU DECOMPOSITION

Solution to the linear system equation Ax=b is the basic problem in linear algebra .Theoretically when A is a non-singular square matrix there exists a unique solution x=A^-b,however the inverse of a matrix is typically not easy to compute .So we hope to transform A to some triangular systems which are much easier to solve by forward or backward substitution ,this process is reffered to as Gaussian elimination [5].This process can be summarized in matrix form as LU DECOMPOSITION and a series of evolutions when Matrix A has extra properties.

In [16]:
import numpy as np

In [17]:
import scipy.linalg as la

In [18]:
# create a sample matrix A
A=np.array([[7,8],[6,5]])
print(A)

[[7 8]
 [6 5]]


In [19]:
import scipy.linalg as la

In [27]:
# perfform LU decomposition
P,L,U=la.lu(A)

In [28]:
print("Matrix A:")
print(A)

Matrix A:
[[7 8]
 [6 5]]


In [33]:
print("\nMatrix L:")
print(L)


Matrix L:
[[1.         0.        ]
 [0.85714286 1.        ]]


In [34]:
print(" \Matrix U:")
print(U)

 \Matrix U:
[[ 7.          8.        ]
 [ 0.         -1.85714286]]


# QR DECOMPOSITION

In linear algebra, a QR decomposition, also known as a QR factorization or QU factorization, is a decomposition of a matrix A into a product A = QR of an orthonormal matrix Q and an upper triangular matrix R. QR decomposition is often used to solve the linear least squares problem and is the basis for a particular matrix.

In [ ]:
import numpy as np

In [ ]:
import scipy.linalg as la

In [ ]:
# create a sample Matrix A
A=np.array([[7,8] ,[6,5]])
print(A)

[[7 8]
 [6 5]]


In [ ]:
# Perform QR decomposition
Q,R=la.qr(A)

In [ ]:
print ("Matrix A:")
print(A)

Matrix A:
[[7 8]
 [6 5]]


In [ ]:
print("\northogonal Matrix Q:")
print(Q)


orthogonal Matrix Q:
[[-0.7592566  -0.65079137]
 [-0.65079137  0.7592566 ]]


In [ ]:
print("\nUpper Triangular Matrix R:")
print(R)


Upper Triangular Matrix R:
[[-9.21954446 -9.32800969]
 [ 0.         -1.41004798]]


# SINGULAR VALUE DECOMPOSITION(SVD)

The singular value decomposition of a matrix A is the factorization of A into the product of three matrices A = UDV T where the columns of U and V are orthonormal and the matrix D is diagonal with positive real entries. The SVD is useful in many tasks.

In [ ]:
import numpy as np

In [ ]:
A=np.array([[7,8],[6,5]])
U,S,VT=np.linalg.svd(A)

In [ ]:
print("Matrix A:")
print(A)

Matrix A:
[[7 8]
 [6 5]]


In [ ]:
print("\nMatrix U:")
print(U)


Matrix U:
[[-0.80692127 -0.59065901]
 [-0.59065901  0.80692127]]


In [ ]:
print(np.diag(S))
print("\nTranspose of Mtrix V")
print(VT)

[[13.15383034  0.        ]
 [ 0.          0.98830528]]

Transpose of Mtrix V
[[-0.69883849 -0.7152795 ]
 [ 0.7152795  -0.69883849]]


# EIGENVALUE DECOMPOSITION

Eigendecomposition provides us with a tool to decompose a matrix by discovering the eigenvalues and the eigenvectors. This operation can prove useful since it allows certain matrix operations to be easier to perform and it also tells us important facts about the matrix itself.

In [ ]:
import numpy as np

In [ ]:
A=np.array([[7,8],[6,5]])
eigenvalues,eigenvectors=np.linalg.eig(A)

In [ ]:
print("Matrix A")
print(A)

Matrix A
[[7 8]
 [6 5]]


In [ ]:
print("\nEigenvaues:")
print(eigenvalues)


Eigenvaue:
[13. -1.]


In [ ]:
print("eigenvectors")
print(eigenvectors)

eigenvectors
[[ 0.8        -0.70710678]
 [ 0.6         0.70710678]]
